name: Deploy Worker
on:
    push:
        branches:
            - main
jobs:
    deploy:
        runs-on: ubuntu-latest
        timeout-minutes: 5
        steps:
            - uses: actions/checkout@v4
            - name: Install wrangler v4
              run: npm install --save-dev wrangler@4
            - name: Build & Deploy Worker
              uses: cloudflare/wrangler-action@v4
              with:
                apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
